apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
  namespace: asm-ingress
spec:
  acme:
    email: devops@airasia.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: cluster-issuer
    solvers:
      - http01:
          ingress:
            class: istio